scidoc fix for PR626
llpcarson/ccpp-physics pull request #3
Opened 2021-04-15 20:54 UTC by mzhangw

Here is a doxyen fix for PR626

2021-04-15 22:41 UTC, ligiabernardet approved these changes
Looks good to me. Note that the use of ver="5" in the SDF is compatible with the v5 public release but not with the current master code. In general, the documentation we are putting in master matches v5, and not the master itself. There is an understanding that we will update the documentation before the next public release.

2021-04-15 22:48 UTC, climbfuji commented
> Looks good to me. Note that the use of ver="5" in the SDF is compatible with the v5 public release but not with the current master code. In general, the documentation we are putting in master matches v5, and not the master itself. There is an understanding that we will update the documentation before the next public release.

This is a bit of a problem. The version string in the suite definition file no longer corresponds to the version of the CCPP release, but to the format/syntax of the suite definition file. This is what we agreed to with our NCAR colleagues a few months ago and we made the change to `version="1"` with this understanding. So this must be `version="1"`, not `5`.

2021-04-15 22:54 UTC, climbfuji commented
The meeting minutes for this discussion are here: https://github.com/NCAR/ccpp-framework/wiki/CCPP-Framework-Meeting-Minutes-2020-08-27

2021-04-15 22:55 UTC, climbfuji requested changes
Replace version="5" with version="1" everywhere.

2021-04-15 22:58 UTC, ligiabernardet commented
Sure, but the Scientific Documentation that Laurie is proposing to commit to master is all about the v5 release and lags behind what is actually on trunk. I suggest that we go forward with updating the master with innovations from v5, and we can proceed with additional updates updates of documentation afterwards.

2021-04-15 22:59 UTC, mzhangw commented
Somehow I just updated as Dom requested.

> On Apr 15, 2021, at 4:58 PM, ligiabernardet ***@***.***> wrote:
> 
> 
> Sure, but the Scientific Documentation that Laurie is proposing to commit to master is all about the v5 release and lags behind what is actually on trunk. I suggest that we go forward with updating the master with innovations from v5, and we can proceed with additional updates updates of documentation afterwards.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/llpcarson/ccpp-physics/pull/3#issuecomment-820782898>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AG7TW2WGL6DJIE5C7IDLXUDTI5VR7ANCNFSM43AHP2UQ>.
>

2021-04-15 23:09 UTC, ligiabernardet commented
OK. In this case I believe` lib="ccppphys"` needs to be removed, as it is no longer used in the SDFs.

2021-04-16 02:23 UTC, climbfuji requested changes
Thanks for your changes so far. When release code goes back to the authoritative repositories, it needs to be adjusted to the innovations that have been made in the meantime, and one of them is the agreement on the new SDF syntax. Thus, replacing `lib="ccppphys" ver="5"` (or `lib="ccppphys" ver="1"` in places where you made such changes already) with just `version="1"` is correct.

2021-04-16 02:23 UTC, climbfuji commented on physics/docs/pdftxt/GFSv15p2_suite.txt
> -<suite name="FV3_GFS_v15p2" lib="ccppphys" ver="5">
Please replace `lib="ccppphys" ver="1"` with just `version="1"` to be consistent with the new syntax.

2021-04-16 02:23 UTC, climbfuji commented on physics/docs/pdftxt/GFSv16beta_suite.txt
> -<suite name="FV3_GFS_v16beta" lib="ccppphys" ver="5">
Please replace `lib="ccppphys" ver="1"` with just `version="1"` to be consistent with the new syntax.

2021-04-16 02:23 UTC, climbfuji commented on physics/docs/pdftxt/RRFS_v1alpha_suite.txt
> -<suite name="FV3_RRFS_v1alpha" lib="ccppphys" ver="5">
Please replace `lib="ccppphys" ver="1"` with just `version="1"` to be consistent with the new syntax.

2021-04-16 15:04 UTC, climbfuji approved these changes

2021-04-16 15:06 UTC, merged

2021-04-16 15:08 UTC, mzhangw commented
Issue https://github.com/NCAR/ccpp-physics/issues/581 is solved

On Fri, Apr 16, 2021 at 9:07 AM Laurie Carson ***@***.***>
wrote:

> Merged #3 <https://github.com/llpcarson/ccpp-physics/pull/3> into
> updates_from_v2.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/llpcarson/ccpp-physics/pull/3#event-4605371551>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG7TW2TCDNPZ7PYKWGR6ZM3TJBHBXANCNFSM43AHP2UQ>
> .
>

2021-04-16 15:11 UTC, climbfuji commented
> [NCAR#581](https://github.com/NCAR/ccpp-physics/issues/581) is solved

Thanks @mzhangw . Laurie, please addd to the description of your PR
> Fixes #581
so that the issue gets closed once your code gets merged. Thanks!